# JINHAK AI 보안 SAST 설정 (Semgrep)
#
# 사용법:
#   npx semgrep --config .semgreprc.yml src/
#
# 참고: security/FORBIDDEN_PATTERNS.md의 12개 금지 패턴 기반
# 버전: JINHAK AI 보안 가이드레일 v2.0

rules:
  # 패턴 1: eval() / Function() 동적 코드 실행 금지
  - id: jinhak-no-eval
    patterns:
      - pattern-either:
          - pattern: eval(...)
          - pattern: new Function(...)
          - pattern: Function(...)
    message: >
      eval()/Function() 사용 금지 - 동적 코드 실행은 코드 인젝션 위험이 있습니다.
      대안: JSON.parse(), 안전한 파서 라이브러리, 또는 설정 기반 분기 사용
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 2: child_process.exec() + 문자열 연결 (커맨드 인젝션)
  - id: jinhak-no-exec-concat
    patterns:
      - pattern: exec($CMD + ...)
      - pattern: exec(`...${...}...`)
    message: >
      child_process.exec()에 동적 문자열 전달 금지 - 커맨드 인젝션 위험.
      대안: execFile()에 인자 배열로 전달, 또는 입력값 화이트리스트 검증
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 4: 취약한 해시 알고리즘 (MD5, SHA1)
  - id: jinhak-no-weak-hash
    patterns:
      - pattern-either:
          - pattern: crypto.createHash('md5')
          - pattern: crypto.createHash("md5")
          - pattern: crypto.createHash('sha1')
          - pattern: crypto.createHash("sha1")
    message: >
      MD5/SHA1은 취약한 해시 알고리즘입니다.
      대안: SHA-256 이상 사용 (crypto.createHash('sha256'))
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 6: 무제한 CORS 설정
  - id: jinhak-no-wildcard-cors
    patterns:
      - pattern: "cors({ origin: '*' })"
      - pattern: "cors({origin: '*'})"
    message: >
      프로덕션에서 CORS origin '*' 사용 금지 - 모든 도메인의 접근을 허용합니다.
      대안: 허용 도메인 목록을 명시적으로 지정
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 8: SQL 문자열 연결 (SQL Injection)
  - id: jinhak-no-sql-concat
    patterns:
      - pattern-either:
          - pattern: $QUERY = "..." + $VAR + "..."
          - pattern: $QUERY = `...${...}...`
    message: >
      SQL 문자열 연결 금지 - SQL Injection 위험.
      대안: Prisma ORM, $queryRaw 템플릿 리터럴, 또는 파라미터화 쿼리 사용
    severity: ERROR
    languages: [javascript, typescript]
    metadata:
      cwe: "CWE-89"

  # 패턴 9: 스택 트레이스 노출
  - id: jinhak-no-stack-expose
    patterns:
      - pattern-either:
          - pattern: res.send(error.stack)
          - pattern: res.json({..., stack: error.stack, ...})
          - pattern: res.send($ERR.stack)
    message: >
      에러 스택 트레이스를 응답에 직접 노출 금지 - 내부 시스템 정보 유출.
      대안: 구조화된 에러 로깅(Winston/Pino) + 사용자에게는 일반적 메시지만 반환
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 10: JWT 알고리즘 미지정
  - id: jinhak-jwt-algorithm
    patterns:
      - pattern: jwt.verify($TOKEN, $SECRET)
    message: >
      jwt.verify()에 알고리즘을 반드시 지정하세요 - 알고리즘 혼동 공격 위험.
      대안: jwt.verify(token, secret, { algorithms: ['HS256'] })
    severity: ERROR
    languages: [javascript, typescript]

  # 패턴 11: 보안 목적 Math.random() 사용
  - id: jinhak-no-math-random-security
    patterns:
      - pattern-either:
          - pattern: |
              $TOKEN = ... Math.random() ...
          - pattern: |
              $SECRET = ... Math.random() ...
          - pattern: |
              $KEY = ... Math.random() ...
    message: >
      보안 목적으로 Math.random() 사용 금지 - 예측 가능한 난수입니다.
      대안: crypto.randomBytes() 또는 crypto.randomUUID() 사용
    severity: ERROR
    languages: [javascript, typescript]

  # 추가: dangerouslySetInnerHTML 사용 감지
  - id: jinhak-no-dangerous-html
    patterns:
      - pattern: dangerouslySetInnerHTML={...}
    message: >
      dangerouslySetInnerHTML 사용 주의 - XSS 위험.
      반드시 DOMPurify 등으로 sanitize한 후 사용하세요.
    severity: WARNING
    languages: [javascript, typescript]

  # 추가: 하드코딩된 비밀번호/토큰 감지
  - id: jinhak-no-hardcoded-secret
    patterns:
      - pattern-either:
          - pattern: |
              password = "..."
          - pattern: |
              apiKey = "..."
          - pattern: |
              api_key = "..."
          - pattern: |
              secret = "..."
    message: >
      비밀번호/API 키 하드코딩 금지 - 환경 변수 또는 Vault를 사용하세요.
    severity: ERROR
    languages: [javascript, typescript]
